### ISSUE TITLE
archive_unless_directed fails when 'has' parameter is not Array

### ISSUE THREAD

**Issue by iceboundflame** [antifuchs/gmail-britta#11]
Hey there,

This tool seems very useful! I was trying it out and ran into the following issue:

```
#!/bin/env ruby

require 'rubygems'
require 'gmail-britta'

fs = GmailBritta.filterset(:me => ['me@example.com']) do
  filter {
    has 'from:friend'
    label 'friend-label'
  }.archive_unless_directed
end
puts fs.generate
```

```
% ruby test.rb
~/.gem/ruby/2.0.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter.rb:191:in `merge_positive_criteria': no implicit conversion of String into Array (TypeError)
    from ~/.gem/ruby/2.0.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter.rb:123:in `archive_unless_directed'
    from test.rb:10:in `block in <main>'
    from ~/.gem/ruby/2.0.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:71:in `instance_eval'
    from ~/.gem/ruby/2.0.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:71:in `perform'
    from ~/.gem/ruby/2.0.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:28:in `rules'
    from ~/.gem/ruby/2.0.0/gems/gmail-britta-0.1.6/lib/gmail-britta.rb:29:in `filterset'
    from test.rb:6:in `<main>'
```

It works as long as I don't use "archive_unless_directed", looks like it's having some kind of problem constructing the negative rule? It works fine if I wrap the 'has' arg in an array.

Thanks.

**Comment by antifuchs** [comment]
This should be fixed by #27 - if you're still running into this (super sorry for sitting on this for 3.5 years!), feel free to test that branch out!
